# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Chris <goabonga@pm.me>
---

- name: Restart gitea
  ansible.builtin.systemd_service:
    name: gitea
    state: restarted
    daemon_reload: true

- name: Restart the certificate renewal timer
  ansible.builtin.systemd_service:
    name: "{{ gitea_tls_renew_unit }}.timer"
    state: restarted
    daemon_reload: true
